### ISSUE TITLE
outputHeadOrientationX: unrecognized selector sent to instance

### ISSUE THREAD

**Issue by mponizil** [tarngerine/oculus-dk2-quartz-composer#1]
Having this issue whenever I try to play the viewer since futzing with the Reset toggle. Have tried turning Oculus on/off after Quartz quits. Now I don't have anything going into Reset.

Quartz Composer Version 4.6.1 (151.2)

`-[Oculus_Rift_DK2PlugIn outputHeadOrientationX]: unrecognized selector sent to instance 0x7f9431d8ff40`

```
0x8afe04c0: -[QCContext nextExecutionTimeForPatch:time:arguments:]
0x8afe016d: -[QCGraphicsContext nextExecutionTimeForPatch:time:arguments:]
0x8afdff7c: -[QCOpenGLContext nextExecutionTimeForPatch:time:arguments:]
0x8b09c355: -[QCView nextExecutionTime:arguments:]
0x033f7101
0x8b09c597: -[QCView render:arguments:]
0x8b09c1cf: -[QCView _renderTimer]
0x8b0700ef: _TimerCallback
0x90b17b64: __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__
0x90b177f3: __CFRunLoopDoTimer
0x90b8adbd: __CFRunLoopDoTimers
0x90ad4288: __CFRunLoopRun
0x90ad3858: CFRunLoopRunSpecific
0x8c83caef: RunCurrentEventLoopInMode
0x8c83c86a: ReceiveNextEventCommon
0x8c83c6ab: _BlockUntilNextEventMatchingListInModeWithFilter
0x91130f81: _DPSNextEvent
0x91130730: -[NSApplication nextEventMatchingMask:untilDate:inMode:dequeue:]
0x91124593: -[NSApplication run]
```

Thanks for your work on this plugin.

**Comment by tarngerine** [comment]
Thanks for the report Misha. I won't be able to debug this this week but in the meantime if it still works without hitting reset you could make your own reset macro with a series of sample and holds + math patches

**Comment by mponizil** [comment]
Hey @tarngerine thanks for checking in. No worries and thanks for the suggestion. I may try poking around with that idea.

**Comment by tarngerine** [comment]
hey landed a pull request that tries to fix it. unfortunately i dont have my dk2 on hand (Traveling) but i basically added more checks to prevent interaction with outputHeadOrientationX/Y/Z if they are not valid. try redownloading and let me know if it still crashes?

**Comment by mponizil** [comment]
Cool! I'm afraid I'm out of town for the next week but will check it out when I get back. Thanks!

**Comment by tarngerine** [comment]
marking as fixed
